apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-ci-cd
  labels:
    app: k8s-ci-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-ci-cd
  template:
    metadata:
      labels:
        app: k8s-ci-cd
    spec:
      containers:
        - name: k8s-ci-cd
          image: croymen/k8s-ci-cd:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: k8s-ci-cd
spec:
  selector:
    app: k8s-ci-cd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
